### ISSUE TITLE
Screen goes black while playing a fullscreen Video in BigSur

### ISSUE THREAD

**Issue by iamjasonkendrick** [EETagent/T480-OpenCore-Hackintosh#72] opened 2021-01-20 04:08 UTC
In BigSur, When I tried to play a youtube video on full-screen mode, the screen goes black but the audio works fine. The only way to go back to normal is to restart the System.

**Comment by EETagent** [comment] 2021-01-25 18:08
Duplicate of #60

**Closed by EETagent** 2021-01-25 18:08 UTC
Labels: duplicate
